// Code generated by "stringer -type=Exception"; DO NOT EDIT.

package mbserver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[IllegalFunction-1]
	_ = x[IllegalDataAddress-2]
	_ = x[IllegalDataValue-3]
	_ = x[SlaveDeviceFailure-4]
	_ = x[AcknowledgeSlave-5]
	_ = x[SlaveDeviceBusy-6]
	_ = x[NegativeAcknowledge-7]
	_ = x[MemoryParityError-8]
	_ = x[GatewayPathUnavailable-10]
	_ = x[GatewayTargetDeviceFailedToRespond-11]
}

const (
	_Exception_name_0 = "SuccessIllegalFunctionIllegalDataAddressIllegalDataValueSlaveDeviceFailureAcknowledgeSlaveSlaveDeviceBusyNegativeAcknowledgeMemoryParityError"
	_Exception_name_1 = "GatewayPathUnavailableGatewayTargetDeviceFailedToRespond"
)

var (
	_Exception_index_0 = [...]uint8{0, 7, 22, 40, 56, 74, 90, 105, 124, 141}
	_Exception_index_1 = [...]uint8{0, 22, 56}
)

func (i Exception) String() string {
	switch {
	case i <= 8:
		return _Exception_name_0[_Exception_index_0[i]:_Exception_index_0[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _Exception_name_1[_Exception_index_1[i]:_Exception_index_1[i+1]]
	default:
		return "Exception(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
